clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

when:
  - branch: [main]
    event: push

steps:
  prepare:
    image: hentioe/openwrt-build-base:23.05-ubuntu
    pull: true
    commands:
      # 修正仓库文件权限
      - sudo chown -R 1000:1000 .
      # 设置并输出环境信息
      - export OPENWRT_BRANCH=23.05
      - "echo Build branch: $${OPENWRT_BRANCH}"
      - export HOME=/home/openwrt-builder
      - "echo User home: $${HOME}"
      - ./scripts/prepare.sh

  build:
    image: hentioe/openwrt-build-base:23.05-ubuntu
    commands:
      - export HOME=/home/openwrt-builder
      - "echo User home: $${HOME}"
      - ./scripts/build.sh

  copy-artifacts:
    image: hentioe/openwrt-build-base:23.05-ubuntu
    commands:
      # 预定义变量
      - export TARGET_ROOT=build/openwrt/bin/targets/rockchip/armv8
      - export EXT4_SYSUPGRADE_IMG_GZ=openwrt-rockchip-armv8-friendlyarm_nanopi-r5s-ext4-sysupgrade.img.gz
      - export SQUASHFS_SYSUPGRADE_IMG_GZ=openwrt-rockchip-armv8-friendlyarm_nanopi-r5s-squashfs-sysupgrade.img.gz
      # 将固件复制到外部
      - cp $${TARGET_ROOT}/$${EXT4_SYSUPGRADE_IMG_GZ} /dist/
      - cp $${TARGET_ROOT}/$${SQUASHFS_SYSUPGRADE_IMG_GZ} /dist/
      # 打印 sha256sums
      - cat $${TARGET_ROOT}/sha256sums
    volumes:
      - ${APPS_HOME}/openwrt/dist:/dist
